# Generated by Django 5.2.5 on 2025-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bikecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikecard',
            name='image',
            field=models.ImageField(upload_to='bikescard/'),
        ),
    ]
