# Generated by Django 5.2.5 on 2025-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_bikecard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikecard',
            name='image',
            field=models.ImageField(upload_to='bike_card/'),
        ),
    ]
