# Generated by Django 5.2.5 on 2025-09-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_bikecard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Over 15000+ Satisfied Customers', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='bikecard',
            name='image',
            field=models.ImageField(upload_to='bikesname/'),
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome class, e.g. fa-motorcycle', max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='website.companystats')),
            ],
        ),
    ]
