# Generated by Django 5.2.5 on 2025-09-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('background', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
