# Generated by Django 5.2.5 on 2025-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='sell/')),
                ('title', models.CharField(default='Sell Fast By DriveRP', max_length=100)),
                ('subtitle', models.CharField(default='Enter Your Details', max_length=100)),
                ('brand_name', models.CharField(default='Brand Name', max_length=100)),
                ('model', models.CharField(default='Model', max_length=100)),
                ('variant', models.CharField(default='Variant', max_length=100)),
                ('year', models.CharField(default='Year', max_length=100)),
                ('kms_driven', models.CharField(default='KMs Driven', max_length=100)),
                ('owner', models.CharField(default='Owner', max_length=100)),
                ('get_price', models.CharField(default='Get Price', max_length=100)),
            ],
        ),
    ]
