# Generated by Django 5.2.5 on 2025-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_howitworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
            ],
        ),
    ]
