# Generated by Django 5.2.6 on 2025-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=100)),
                ('description', models.TextField()),
                ('background', models.ImageField(upload_to='mission/')),
            ],
        ),
    ]
