# Generated by Django 5.2.6 on 2025-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='approach/')),
                ('position', models.CharField(choices=[('top_left', 'Top Left'), ('bottom_left_1', 'Bottom Left 1'), ('bottom_left_2', 'Bottom Left 2'), ('right_long', 'Right Long')], max_length=20)),
            ],
        ),
    ]
