# Generated by Django 5.2.6 on 2025-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_loginimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('engine_cc', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(default='Petrol', max_length=50)),
                ('owner', models.CharField(default='1st Owner', max_length=50)),
                ('image', models.ImageField(upload_to='bikes/')),
            ],
        ),
    ]
