# Generated by Django 5.2.5 on 2025-09-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_buybike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DriveRP Logo', max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
