# Generated by Django 5.2.5 on 2025-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='footer/bikes/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DriveRP Footer Logo', max_length=100)),
                ('image', models.ImageField(upload_to='footer/logo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='footer/social/')),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
