# Generated by Django 5.2.6 on 2025-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_footerbike_footerlogo_socialicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('engine_cc', models.CharField(max_length=50)),
                ('kilometers', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bikes/')),
            ],
        ),
        migrations.DeleteModel(
            name='BuyBike',
        ),
    ]
