# Generated by Django 5.2.6 on 2025-09-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_filtercard_delete_buybike'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercard',
            name='location',
            field=models.CharField(default='Tamil Nadu', max_length=200),
        ),
        migrations.AlterField(
            model_name='bikecard',
            name='location',
            field=models.CharField(default='Tamil Nadu', max_length=200),
        ),
    ]
