# Generated by Django 5.2.5 on 2025-09-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_filtercard_location_alter_bikecard_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='buybike/')),
            ],
        ),
    ]
