# Generated by Django 5.2.6 on 2025-09-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_buybike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='payment_icons/')),
            ],
        ),
    ]
