# Generated by Django 5.2.6 on 2025-09-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='riders/')),
            ],
        ),
    ]
