# Generated by Django 5.2.6 on 2025-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_bikerider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_rider_image', models.ImageField(upload_to='fastrider/')),
                ('quote', models.TextField()),
            ],
        ),
    ]
