# Generated by Django 5.2.6 on 2025-09-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_feature_delete_supportfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialicon',
            name='link',
        ),
    ]
