# Generated by Django 5.2.6 on 2025-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_socialicon_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('make_year', models.CharField(max_length=10)),
                ('refurbished', models.CharField(default='No', max_length=10)),
                ('rto_state', models.CharField(max_length=100)),
                ('rto_city', models.CharField(max_length=100)),
                ('registration_year', models.CharField(blank=True, max_length=10, null=True)),
                ('kilometers', models.CharField(max_length=50)),
                ('owners', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('registration_certificate', models.CharField(default='No', max_length=10)),
                ('finance', models.CharField(default='No', max_length=10)),
                ('insurance', models.CharField(default='No', max_length=10)),
                ('warranty', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
