# Generated by Django 5.2.6 on 2025-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_bookingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('ignition_type', models.CharField(max_length=100)),
                ('transmission_type', models.CharField(max_length=100)),
                ('front_brake_type', models.CharField(max_length=100)),
                ('rear_brake_type', models.CharField(max_length=100)),
                ('abs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('odometer', models.CharField(max_length=100)),
                ('wheel_type', models.CharField(max_length=100)),
            ],
        ),
    ]
