# Generated by Django 5.2.6 on 2025-09-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_bikespecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='confirmation/')),
                ('message_title', models.CharField(default='Booking Confirmed', max_length=100)),
                ('message_text', models.CharField(default='The Bike is Yours – Enjoy Your Journey', max_length=200)),
            ],
        ),
    ]
